---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Ensure /var/www/html directory has correct permissions.
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data

    - name: Ensure .ssh directory exists.
      file:
        path: /var/www/.ssh
        state: directory
        mode: 0700
        owner: www-data
        group: www-data
    - name: add github ssh key
      copy: >
        src=files/id_rsa.github
        dest=/root/.ssh/id_rsa.github
        owner=root
        group=root
        mode=0600
  
    - name: configure ssh to use ansible key for github.com
      template: >
        src=files/ssh_config.j2
        dest=/root/.ssh/config
        owner=root
        group=root
        mode=0644
      
    - name: clone a private repository
      git: >
        repo=ssh://git@github.com/avidnyat/lamp-laravel.git
        key_file=/root/.ssh/id_rsa.github
        dest=/var/www/html/releases/release_{{ version }}
# See: https://stackoverflow.com/a/37096534/100134
    - name: Ensure setfacl support is present.
      package: name=acl

